variable "yandex_token" {
  default     = ""
  type        = string
  description = "Yandex token generated by yc"
  sensitive   = true
  nullable    = false
}

variable "cloud_id" {
  default     = "b1g3jddf4nv5e9okle7p"
  type        = string
  description = "Id of cloud"
  sensitive   = false
  nullable    = false
}

variable "folder_id" {
  default     = "b1g4v2q4j0dfegi3pmsc"
  type        = string
  description = "Id of folder for current group"
  sensitive   = false
  nullable    = false
}

# to avoid error need to pass variable yandex_token to command line
# example: terraform apply -var="yandex_token=$YC_TOKEN"
provider "yandex" {
  cloud_id  = var.cloud_id
  folder_id = var.folder_id
  zone      = "ru-central1-a"
  token     = var.yandex_token
}